name: Generate postman collection and update if changed

on:
  workflow_dispatch:  
     inputs:
      name:
        description: 'Why are you running manually?'
        default: 'just cuz'
  #schedule:
    # Runs every 30th day at midnight
  #  - cron: '0 0 */30 * *'

jobs:

  generate-collection:
    runs-on: ubuntu-latest

    steps:

      - name: checkout repo
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v1
        with:
          python-version: '3.9.x'
          
      - name: install python module requests
        run: pip install requests

      - name: Install NVM
        run: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash

      - name: Install NPM
        run: nvm install node

      - name: Install openapi-to-postman
        run: npm i -g openapi-to-postmanv2      
  
      - name: Pull latest OpenAPI specs from Reltio Swagger
        run: python reltio_postman_gen.py

      - name: Convert OpenAPI spec to Postman Collection
        run: openapi2postmanv2 -s openApispec/Configuration.json -o collections/generated/Configuration.json -p -O folderStrategy=Tags,includeAuthInfoInExample=false,requestNameSource=URL,parametersResolution=Schema

